### ISSUE TITLE
Failed to write_lines: Futures timing out

### ISSUE THREAD

**Issue by sr-bentley** [broadinstitute/gatk-sv#105]
## (Configuration) Bug Report
Not a true bug as it is not being run as intended: Running on HPC slurm and singularity

### Affected module(s) or script(s)
GATKSVPipelineSingleSample
GermlineCNVCase.wdl : GermlineCNVCallerCaseMode 

### Affected version(s)
master: 0a6fcf136f632e5b324a7d8a65b9e9e7c69399ba

### Description 
Hi everyone - not sure if anyone has come across this error before. I'm running the GATKSVPipelineSingleSample workflow on a HPC via slurm with singularity. I'm facing the following error in CNVGermlineCaseWorkflow which requeues a couple of times but doesn't resolve. Across 285 scatter jobs, only 110 finish.

<code>
Failed to write_lines(...) (reason 1 of 1): Futures timed out after [10 minutes]
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:89)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:85)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:612)
        ... 41 common frames omitted
</code>

I'm suspecting this is due to some incompatibility on the local & singularity system - but has anyone seen something similar?
I see some suggestions that increasing mem _may_ help.. I was using 10gb across 4 CPUs (walltime =24hrs) and upping that to 30Gb has not solved the issue. Tracking one of the timeouts, it had timed out 5 times over a space of ~90 minutes.
The input files (hardlinks) have a size >0 , and I can access them after the fail.

----
Example of error log:
<code>
2021-01-30 21:42:38,962 ERROR - DispatchedConfigAsyncJobExecutionActor [UUID(7239e136)CNVGermlineCaseWorkflow.GermlineCNVCallerCaseMode:92:1]: Error attempting to Execute
java.lang.Exception: Failed command instantiation
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:614)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand$(StandardAsyncExecutionActor.scala:549)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.instantiatedCommand$lzycompute(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.instantiatedCommand(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents(StandardAsyncExecutionActor.scala:326)
        at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents$(StandardAsyncExecutionActor.scala:325)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.commandScriptContents(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.writeScriptContents(SharedFileSystemAsyncJobExecutionActor.scala:175)
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.writeScriptContents$(SharedFileSystemAsyncJobExecutionActor.scala:174)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.writeScriptContents(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute(SharedFileSystemAsyncJobExecutionActor.scala:158)
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute$(SharedFileSystemAsyncJobExecutionActor.scala:155)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.execute(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$executeAsync$1(StandardAsyncExecutionActor.scala:677)
        at scala.util.Try$.apply(Try.scala:213)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync(StandardAsyncExecutionActor.scala:677)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync$(StandardAsyncExecutionActor.scala:677)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeAsync(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:1000)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:992)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeOrRecover(ConfigAsyncJobExecutionActor.scala:215)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:38)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.aroundReceive(ConfigAsyncJobExecutionActor.scala:215)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: common.exception.AggregatedMessageException: Error(s):
Failed to write_lines(...) (reason 1 of 1): Futures timed out after [10 minutes]
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:89)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:85)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:612)
        ... 41 common frames omitted
</code>

-----

#### Steps to reproduce
To use workflow locally with singularity some edits were required:
1) locally download all required datasets (these were checked on failed jobs - can open)
2) gunzip converted to gunzip -f
3) /root/ and other docker-only paths removed
4) removed cloud credentials
5) Instead of samtools_cloud_docker and marketplace ubuntu, using sv_base_mini_docker
6) Reset LD_PATHs

I'm using the NA12878_24RG_med.hg38.bam sample from gs://gatk-test-data/wgs_bam/NA12878_24RG_hg38/NA12878_24RG_med.hg38.bam - randomly subsetted to 25% via samtools view -bs 500.25

cromwell 47 is being run

Each scattered job is given 1 day and 10gb of mem across 4 CPUs to run

#### Expected behavior
For the timeouts to occur less frequently. And requeued timeouts resolve.

#### Actual behavior
Sporadically times out, never recovers.

**Comment by cwhelan** [comment]
Hi, I haven't seen this error before, but it sounds like an issue coming from within Cromwell itself rather than SV pipeline code. Two suggestions: give more memory to cromwell itself (as opposed to the runtimes of the tasks -- apologies if this is what you are already doing, but your description made it sound like you are giving more memory to the tasks rather than the cromwell process) or try upgrading cromwell to the most recent version to see if any recent bug fixes might have helped with this.

**Comment by sr-bentley** [comment]
Thanks for the response - turns out the issue came from one layer above - slurm's --wait.

We've successful applied the fix mentioned here : https://github.com/broadinstitute/cromwell/issues/5218

Thanks again
