### ISSUE TITLE
Module00c TinyResolve: StopIteration

### ISSUE THREAD

**Issue by ghzhaole** [broadinstitute/gatk-sv#122]
Module00c TinyResolve

When running Module00c-TinyResolve, the following error reported:
```
Traceback (most recent call last):
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cli/resolve.py", line 231, in resolve_complex_sv
    cpx = ComplexSV(cluster, cytobands, mei_bed, SR_only_cutoff)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 38, in __init__
    self.resolve(SR_only_cutoff=SR_only_cutoff)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 82, in resolve
    self.resolve_translocation()
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 278, in resolve_translocation
    armA, armB = get_arms(plus, self.cytobands)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 650, in get_arms
    return _get_arm(regionA), _get_arm(regionB)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 643, in _get_arm
    arm = next(cytobands.fetch(region))
  File "pysam/libctabix.pyx", line 673, in pysam.libctabix.TabixIterator.__next__
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luohx/software/anaconda3/envs/cromwell/bin/svtk", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/scripts/svtk", line 67, in <module>
    main()
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/scripts/svtk", line 64, in main
    getattr(cli, command)(sys.argv[2:])
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cli/resolve.py", line 481, in main
    for record in resolve_complex_sv(vcf, cytobands, disc_pairs, mei_bed, args.prefix,
RuntimeError: generator raised StopIteration
```

Here is the command:
```
bash mantatloccheck.sh std_000.manta.100001.vcf.gz 100001.disc.txt.gz 100001 hg38_v0_sv-resources_resources_v1_mei_hg38.bed.gz hg38_v0_sv-resources_resources_v1_cytobands_hg38.bed.gz
```

The error is produced by capturing the wrong region that dosen't match the cytoband file.

I check the error line of std_000.manta.100001.vcf.gz file:
```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  100001
chr1    88507127    manta_100001_248    N   [chr17:33736831[N   .   PASS    END=33736831;SVTYPE=BND;CHR2=chr17;STRANDS=--;SVLEN=-1;ALGORITHMS=manta;EVIDENCE=PE;MEMBERS=manta_100001_248	GT:manta    0/1:1
chr1    88507142    manta_100001_249    N   N]chr17:33737644]   .   PASS    END=33737644;SVTYPE=BND;CHR2=chr17;STRANDS=++;SVLEN=-1;ALGORITHMS=manta;EVIDENCE=PE;MEMBERS=manta_100001_249	GT:manta    0/1:1
```

The pos "33737644" is supposed to be extracted with chr17 but "88507142" is wrongly extracted which causes the bug. 

Could you please help me out with this issue? 
Thanks in advance!

**Comment by mwalker174** [comment]
I happened to notice you have a sample named `100001`. We've had numeric IDs cause issues in the past and would strongly suggest you use something like the script in `InternalSampleID` in `GetSampleID.wdl` to generate safe internal IDs for processing. There are also issues if any ID is a substring of another or if they contain the string `name`. If all your ID's are numbers like this, surrounding them with underscores `_` may suffice eg `_100001_`.

**Comment by mwalker174** [comment]
@ghzhaole Were you able to work through this error?

**Comment by mwalker174** [comment]
Stale issue
