### ISSUE TITLE
GenotypeBatch: svtk count error

### ISSUE THREAD

**Issue by arosato87** [broadinstitute/gatk-sv#327]
### Affected module(s) or script(s)
_Module/script name(s), special parameters?_
call-GenotypeBatch -> call-GenotypePESRPart2 -> call-CountSRBca 

### Affected version(s)
- [ ] Latest master branch as of [Feb 22 2022]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

I am running the GATK-SV pipeline in Single sample mode (GATKSVPipelineSingleSample.wdl) with the test input file proved (test_GATKSVPipelineSingleSample.ref_panel_1kg.na12878.no_melt.json). I am running the program with a cromwell HPC backend that I have configured to work with an LSF HPC system (LSF_singu_4.config). I am running the pipeline with the one NA12878 test sample specified in the GATKSVPipelineSingleSample.ref_panel_1kg.na12878.no_melt.json file I based my input file on. 

Inside the execution script for the call-CountSRBca module (code generated by the CountSR task in the TasksGenotypeBatch.wdl) my job will run up until it encounters the line with the svtk command: 
`svtk count-sr -s ~{write_lines(samples)} --medianfile ~{medianfile} ~{vcf} local.SR.txt.gz ~{prefix}.sr_counts.txt`
The command with my HPC pathing:
`svtk count-sr -s /cromwell-executions/GATKSVPipelineSingleSample/1681c241-c1f7-478d-99b1-5b061475c6fb/call-GenotypeBatch/GenotypeBatch/3f0f008b-7cc7-419e-b955-ea7b7590758d/call-GenotypePESRPart2/GenotypePESRPart2/792ae6e5-6583-40ce-b662-3d9f11ad8b00/call-CountSRBca/shard-0/attempt-2/execution/write_lines_316220c6f11b746ff9b6cdff48e70640.tmp --medianfile /cromwell-executions/GATKSVPipelineSingleSample/1681c241-c1f7-478d-99b1-5b061475c6fb/call-GenotypeBatch/GenotypeBatch/3f0f008b-7cc7-419e-b955-ea7b7590758d/call-GenotypePESRPart2/GenotypePESRPart2/792ae6e5-6583-40ce-b662-3d9f11ad8b00/call-CountSRBca/shard-0/attempt-2/inputs/1308181802/test_NA12878_medianCov.transposed.bed /cromwell-executions/GATKSVPipelineSingleSample/1681c241-c1f7-478d-99b1-5b061475c6fb/call-GenotypeBatch/GenotypeBatch/3f0f008b-7cc7-419e-b955-ea7b7590758d/call-GenotypePESRPart2/GenotypePESRPart2/792ae6e5-6583-40ce-b662-3d9f11ad8b00/call-CountSRBca/shard-0/attempt-2/inputs/-1356191980/bca.aaaaaa.vcf.gz local.SR.txt.gz bca.aaaaaa.vcf.gz.sr_counts.txt`

It attempts to run this command and the program exits with a stack trace indicating there is an invalid character in the command input data. 

> Traceback (most recent call last):
  File "/opt/conda/bin/svtk", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/svtk/scripts/svtk", line 68, in <module>
    main()
  File "/opt/svtk/scripts/svtk", line 65, in main
    getattr(cli, command)(sys.argv[2:])
  File "/opt/svtk/svtk/cli/pesr_test.py", line 326, in count_sr
    counts = counts.reindex(whitelist).fillna(0).astype(int)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 700, in astype_nansafe
    "Cannot convert non-finite values (NA or inf) to " "integer"
ValueError: Cannot convert non-finite values (NA or inf) to integer

I have searched these input files for NA and inf values, but have had no success finding anything that would violate the datatype requirement. Even if entries in the VCF file were to violate the input datatype requirement, I would naively think/suggest the program would be designed to throw out those invalid vcf entries and continue with the valid ones.

#### Steps to reproduce
[local.SR.txt.gz](https://github.com/broadinstitute/gatk-sv/files/8398770/local.SR.txt.gz)
[bca.aaaaaa.vcf.gz](https://github.com/broadinstitute/gatk-sv/files/8398771/bca.aaaaaa.vcf.gz)
[bca.aaaaaa.vcf.gz.sr_counts.txt](https://github.com/broadinstitute/gatk-sv/files/8398776/bca.aaaaaa.vcf.gz.sr_counts.txt)

_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem._

If you want to reproduce my error exactly a docker or singularity environment should be setup running the us.gcr.io/broad-dsde-methods/eph/sv-pipeline@sha256:b01b9531d5ba68896581ad5dfa68beb5b0cce2c22291cc9e81eea6047db9cee3 docker image and the following command should be run with the input files I've provided.
`svtk count-sr -s write_lines_316220c6f11b746ff9b6cdff48e70640.tmp --medianfile test_NA12878_medianCov.transposed.bed bca.aaaaaa.vcf.gz  local.SR.txt.gz bca.aaaaaa.vcf.gz.sr_counts.txt`

#### Expected behavior
The command should run without error and populate the bca.aaaaaa.vcf.gz file with data.

#### Actual behavior
The command exists with an error and the bca.aaaaaa.vcf.gz file is written empty with only the header. The GATK_SV pipeline fails to run the next steps without successful completion of the module.

**Comment by mwalker174** [comment]
Hi @arosato87 thanks for reporting this. Can you please provide the mediancov and samples files as well so we can reproduce the issue? My suspicion is there is a "0" somewhere in medians file, since that would cause a division-by-zero when normalizing the counts, which could generate the error you are seeing.

**Comment by leedchou** [comment]
> 

Hi @mwalker174,

The same error , and I found the median coverage of my test sample is '0'. I am wondering how it comes?
The test sample is **NA12878**.

**Median file** is like:
NA12878	HG00096	HG00129	HG00140	HG00150	HG00187	HG00239	HG00277	HG00288	HG00337	HG00349	HG00375	HG00410	HG00457	HG00557	HG00599	HG00625	HG00701	HG00740	HG00844	HG01060	HG01085	HG01112	HG01275	HG01325	HG01344	HG01356	HG01384	HG01393	HG01396	HG01474	HG01507	HG01572	HG01607	HG01709	HG01747	HG01790	HG01794	HG01799	HG01861	HG01874	HG01880	HG01885	HG01958	HG01982	HG02002	HG02010	HG02019	HG02020	HG02069	HG02085	HG02186	HG02221	HG02235	HG02272	HG02275	HG02299	HG02332	HG02367	HG02374	HG02489	HG02490	HG02491	HG02586	HG02588	HG02611	HG02620	HG02642	HG02648	HG02658	HG02855	HG02953	HG03007	HG03009	HG03085	HG03099	HG03100	HG03111	HG03369	HG03370	HG03436	HG03449	HG03472	HG03476	HG03556	HG03604	HG03649	HG03684	HG03694	HG03709	HG03722	HG03727	HG03744	HG03756	HG03789	HG03850	HG03864	HG03872	HG03888	HG04118	HG04158	HG04161	HG04183	NA06984	NA10847	NA11894	NA12340	NA12489	NA12872	NA18499	NA18507	NA18530	NA18539	NA18549	NA18553	NA18560	NA18638	NA18923	NA18941	NA18945	NA18956	NA18995	NA19001	NA19035	NA19062	NA19102	NA19143	NA19184	NA19350	NA19351	NA19377	NA19443	NA19449	NA19661	NA19678	NA19679	NA19684	NA19746	NA19795	NA19818	NA19913	NA20126	NA20320	NA20321	NA20346	NA20509	NA20510	NA20522	NA20752	NA20764	NA20802	NA20845	NA20869	NA20895	NA21102	NA21122	NA21133
 0	23	20	22	26	23	24	22	21	21	24	24	23	22	22	22	23	25	22	21	23	21	22	22	22	23	23	22	20	23	21	21	20	21	22	22	21	22	20	23	22	20	22	22	22	22	20	20	20	20	20	22	21	21	23	21	21	22	21	23	23	23	22	21	22	21	21	21	22	21	25	20	21	20	21	23	22	23	28	21	22	23	20	21	22	22	22	22	21	21	22	23	22	22	22	22	23	21	21	22	22	22	29	22	22	22	22	22	28	23	21	22	25	22	23	21	37	22	22	22	21	23	22	24	21	21	21	20	21	22	22	21	22	21	30	22	22	22	21	22	21	21	20	21	22	23	20	21	21	22	22	22	25	22	27	21	29

**Comment by mwalker174** [comment]
Overdue follow-up here, but the problem is that `NA12878` has a median coverage of 0, which is causing the error. This is an edge case we should check for in `svtk`.
