### ISSUE TITLE
Error in ResolveManta of TinyResolve.wdl in GATKSVPipelineSingleSample.wdl

### ISSUE THREAD

**Issue by c2997108** [broadinstitute/gatk-sv#367]
I built build/NA12878/test/GATKSVPipelineSingleSample.no_melt.json with scripts/inputs/build_default_inputs.sh.
Next, I used the following cram file 
ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239334/NA12878.final.cram
and downloaded all gs:// files of GATKSVPipelineSingleSample.no_melt.json to my local server and modified the json file.

GATKSVPipelineSingleSample.wdl was executed with the following command.
java -jar /usr/local/opt/cromwell-78/cromwell-78.jar run -i GATKSVPipelineSingleSample.no_melt.json  wdl/GATKSVPipelineSingleSample.wdl

Then I got the following error. What should I do?

```
[2022-07-02 06:22:41,16] [info] WorkflowManagerActor: Workflow 8fdeff89-b584-41d1-ad84-78eccf4cbd14 failed (during ExecutingWorkflowState): Job TinyResolve.ResolveManta:0:2 exited with return code 1 which has
 not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /data/gatk-sv/gatksv_run/cromwell-executions/GATKSVPipelineSingleSample/8fdeff89-b584-41d1-ad84-78eccf4cbd14/call-GatherBatchEvidence/GatherBa
tchEvidence/8033fb7d-0186-44d8-95e8-08b0ac5b170a/call-TinyResolve/TinyResolve/e0f37699-b5ff-42e1-b90a-2b3f919ce4a7/call-ResolveManta/shard-0/attempt-2/execution/stderr.
 [First 3000 bytes]:[W::tbx_parse1] VCF INFO/END=23845140 is smaller than POS at chr1:28189164
This tag will be ignored. Note: only one invalid END tag will be reported.
[W::tbx_parse1] VCF INFO/END=23845140 is smaller than POS at chr1:28189164
This tag will be ignored. Note: only one invalid END tag will be reported.
sort -k1,1V -k2,2n
Traceback (most recent call last):
  File "/opt/conda/envs/gatk-sv/bin/svtk", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/svtk/scripts/svtk", line 65, in <module>
    main()
  File "/opt/svtk/scripts/svtk", line 62, in main
    getattr(cli, command)(sys.argv[2:])
  File "/opt/svtk/svtk/cli/resolve.py", line 486, in main
    for record in resolve_complex_sv(vcf, cytobands, disc_pairs, mei_bed, args.prefix,
  File "/opt/svtk/svtk/cli/resolve.py", line 223, in resolve_complex_sv
    cpx = ComplexSV(cluster, cytobands, mei_bed, SR_only_cutoff)
  File "/opt/svtk/svtk/cxsv/complex_sv.py", line 35, in __init__
    self.make_record()
  File "/opt/svtk/svtk/cxsv/complex_sv.py", line 615, in make_record
    svu.update_best_genotypes(
  File "/opt/svtk/svtk/utils/genotype_merging.py", line 134, in update_best_genotypes
    best_record = choose_best_genotype(sample, records)
  File "/opt/svtk/svtk/utils/genotype_merging.py", line 47, in choose_best_genotype
    carrier_mingq_index = _get_mingq_index([f for _, f in carrier_format_fields])
  File "/opt/svtk/svtk/utils/genotype_merging.py", line 37, in _get_mingq_index
    gqs = [f['GQ'] for f in format_fields_list]
  File "/opt/svtk/svtk/utils/genotype_merging.py", line 37, in <listcomp>
    gqs = [f['GQ'] for f in format_fields_list]
  File "pysam/libcbcf.pyx", line 3460, in pysam.libcbcf.VariantRecordSample.__getitem__
  File "pysam/libcbcf.pyx", line 796, in pysam.libcbcf.bcf_format_get_value
KeyError: 'invalid FORMAT: GQ'
```

**Comment by mwalker174** [comment]
This appears to have been fixed in #369
