### ISSUE TITLE
Strange results for pe- and sr-tests

### ISSUE THREAD

**Issue by NstVasileva** [broadinstitute/gatk-sv#430]
Hello again!

1) I've got a result from GATK CollectSVEvidence for single sample - everything is okay.

2) Then i standardized my vcf files from manta and delly in svtk-pipeline docker build, bgzip them and made tabix index.

3) I made an vcfcluster for chrom 1, also bgzip stdout and made tabix index. In svtk-pipeline docker build.

4) And then i've started to run sr- and pe-tests. But I've got strange results. Just "0" for everything. Is it okay or something wrong? And if it's wrong - i don't understand what i did wrong.

This is example of pe-test result:

```
name	log_pval	called_median	bg_median	bg_frac
MERGED_1_1	0.0	0.0	0.0	0.0
MERGED_1_2	0.0	0.0	0.0	0.0
MERGED_1_3	0.0	0.0	0.0	0.0
MERGED_1_4	0.0	0.0	0.0	0.0
```

Thank you!

**Comment by mwalker174** [comment]
Hi @NstVasileva, it's hard for us to provide support if you aren't using the WDLs. Are you following the single sample workflow? (see `wdl/GATKSVPipelineSingleSample.wdl`)

**Comment by NstVasileva** [comment]
Hello! Yep, it's single sample workflow.
I've counted SR and Pe tests again and got normal results. 

But from your pipeline i can't understand what do next. In svtk pipeline module 03 - filtering and it describes aggregate.py script. But there is no such script in your docker svtk-pipeline. 

And I have only PE and SR results - i don't want to filter CNVs now.

How can I aggregate PE and SR results only and filter VCF?

**Comment by NstVasileva** [comment]
For WDL pipeline on GoogleCloud I can't get any results. I get the error  

```
2022-11-01` 13:40:13 cromwell-system-akka.dispatchers.engine-dispatcher-91 INFO  - WorkflowManagerActor: Workflow 38212b60-0d4d-48be-b2a0-152
3eed7f723 failed (during ExecutingWorkflowState): java.lang.Exception: Task CramToBam.RunCramToBamRequesterPays:NA:2 failed. The job was sto
pped before the command finished. PAPI error code 9. Please check the log file for more details: gs://my_results_genomics/GATKSVPipelineSing
leSample/38212b60-0d4d-48be-b2a0-1523eed7f723/call-GatherSampleEvidence/GatherSampleEvidence/890564a6-071f-49ad-ad31-3f92a2f2d83b/call-CramT
oBam/CramToBam/225de831-b3e1-46a0-8b18-a374fda270a2/call-RunCramToBamRequesterPays/attempt-2/RunCramToBamRequesterPays.log.
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor$.StandardException(PipelinesApiAsyncBackendJob
ExecutionActor.scala:91)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleFailedRunStatus$1(PipelinesApiAsyncBackendJobExecutionActor.scala:803)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.$anonfun$handleExecutionFailure$1(PipelinesApiAsyncBackendJobExecutionActor.scala:815)
        at scala.util.Try$.apply(Try.scala:210)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:812)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:95)
        at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1341)
        at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1337)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
But I even haven't log file by this path "gs://my_results_genomics/GATKSVPipelineSing
leSample/38212b60-0d4d-48be-b2a0-1523eed7f723/call-GatherSampleEvidence/GatherSampleEvidence/890564a6-071f-49ad-ad31-3f92a2f2d83b/call-CramT
oBam/CramToBam/225de831-b3e1-46a0-8b18-a374fda270a2/call-RunCramToBamRequesterPays/attempt-2/RunCramToBamRequesterPays.log".  

There are only this files there:  

- gcs_delocalization.sh
- gcs_localization.sh
- gcs_transfer.sh
- script  

Have you any idea how can I fix this? Or at least get log file?

**Comment by NstVasileva** [comment]
Or maybe you just have results for NA12878 SingleSample and can share it? I'm interested in filtered vcf to compare with vcf from one manta.

**Comment by mwalker174** [comment]
Yes there's a run under the Job History in the [featured workspace on Terra](https://app.terra.bio/#workspaces/help-gatk/GATK-Structural-Variants-Single-Sample).

**Comment by mwalker174** [comment]
Closing out since this seems to be a backend configuration issue
