### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/gatk-sv#656]
### Instructions

Hi, I had successfully installed svtk and used it correctly, but I'm not sure why it stopped working properly after some time. I wonder if I updated some Python modules. Can you help me with this?

When I tried to use it again, I encountered the following error message.
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/genomeslink.py", line 18, in <module>
    from scipy.sparse import csgraph
ImportError: cannot import name 'csgraph' from 'scipy.sparse' (unknown location)

Subsequently, I upgraded the scipy module, and it resulted in the following error.
Traceback (most recent call last):
  File "/xxx/software/miniconda3/bin/svtk", line 45, in <module>
    import svtk.cli as cli
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/cli/__init__.py", line 12, in <module>
    from .adjudicate import main as adjudicate
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/cli/adjudicate.py", line 14, in <module>
    from svtk.adjudicate import adjudicate_SV
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/adjudicate/__init__.py", line 1, in <module>
    from .random_forest import RandomForest, rf_classify
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/adjudicate/random_forest.py", line 14, in <module>
    from sklearn.ensemble import RandomForestClassifier
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/sklearn/__init__.py", line 84, in <module>
    from .utils._show_versions import show_versions
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/sklearn/utils/_show_versions.py", line 13, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS

I attempted to reinstall svtk again, and here's what I did, but I encountered a similar error. Could you help me resolve it?
git clone https://github.com/talkowski-lab/svtk.git
cd svtk/
python setup.py
Compiling svtk/utils/helpers.pyx because it changed.
[1/1] Cythonizing svtk/utils/helpers.pyx
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: no commands supplied
find -name svtk
./scripts/svtk
./svtk
./scripts/svtk --help
Traceback (most recent call last):
  File "/xxx/software/svtk/./scripts/svtk", line 42, in <module>
    import svtk.cli as cli
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/cli/__init__.py", line 12, in <module>
    from .adjudicate import main as adjudicate
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/cli/adjudicate.py", line 14, in <module>
    from svtk.adjudicate import adjudicate_SV
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/adjudicate/__init__.py", line 1, in <module>
    from .random_forest import RandomForest, rf_classify
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/svtk/adjudicate/random_forest.py", line 14, in <module>
    from sklearn.ensemble import RandomForestClassifier
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/sklearn/__init__.py", line 84, in <module>
    from .utils._show_versions import show_versions
  File "/xxx/software/miniconda3/lib/python3.9/site-packages/sklearn/utils/_show_versions.py", line 13, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS

I tried to replace the Python 3.9 under Miniconda with another Python 3.6 under Anaconda, but I was still unable to use svtk, and it gave me the following error. I think it might be because I didn't install the svtk.cli module. Can you help me with this?
Traceback (most recent call last):
  File "/xxx/software/miniconda3/bin/svtk", line 45, in <module>
    import svtk.cli as cli
ModuleNotFoundError: No module named 'svtk.cli'

pip install svtk.cli
Collecting svtk.cli
  Could not find a version that satisfies the requirement svtk.cli (from versions: )
No matching distribution found for svtk.cli
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

## Bug Report

  File "/xxx/software/miniconda3/lib/python3.9/site-packages/sklearn/utils/_show_versions.py", line 13, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS

Traceback (most recent call last):
  File "/xxx/software/miniconda3/bin/svtk", line 45, in <module>
    import svtk.cli as cli
ModuleNotFoundError: No module named 'svtk.cli'

### Affected version(s)
$ python --version
Python 3.9.7

**Comment by mwalker174** [comment]
Hi @jingydz, the original repo `https://github.com/talkowski-lab/svtk.git` is no longer being maintained. You should use install the svtk module from gatk-sv instead and install:

```
git clone https://github.com/broadinstitute/gatk-sv.git
cd src/svtk/
pipe install -e .
```
